name: dry-transformer
codacy_id: 22edf59617be4aef97cfbe4e1c99f1ce
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Data transformation toolkit"
  runtime_dependencies:
    - ["bigdecimal"]
    - ["zeitwerk", "~> 2.6"]
